name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: textbook/git-checkout-submodule-action@2.1.1
    - name: make
      run: make CHECKTODOS_SCRIPT_ARGS=--no-error
