name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: install-prereqs
      run: ./install-prereqs.sh
    - name: make
      run: make CHECKTODOS_SCRIPT_ARGS=--no-error
